language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - ruby1.8
before_script:
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:migrate'"
script: "bundle exec rspec spec"
