language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
rvm:
  - 2.6
before_install:
  - gem install bundler
before_script:
  - cd spec/dummy; RAILS_ENV=test bundle exec rake db:migrate; cd -
script: bundle exec rspec
